version: "3"
services: 
  app: 
    build: 
      context: ./ 
      dockerfile: app.docker 
    volumes: 
      - ./:/doodle
    ports: 
      - 8081:8081
    environment: 
      PORT: ${PORT}
    restart: always 
    tty: true
